### ISSUE TITLE
Failed to prepare VL53L0X

### ISSUE THREAD

**Issue by stumpf-das** [stm32duino/X-NUCLEO-53L0A1#6]
I'm using a P-NUCLEO-53L0A1 kit consisting of a X-NUCLEO-53L0A1 sensor board, two VL53L0X satellites and a NUCLEO-F401RE board.

Tool chain / Library setup:

Arduino 1.8.12

Board from https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

Libraries:
STM32duino Proximity Gesture version=1.0.4
STM32duino VL53L0X version=1.0.5
STM32duino X-NUCLEO-53L0A1 version=1.0.3

Example: X-NUCLEO-53L0A1_HelloWorld

When I run the example, I get this output:
`Failed to prepare VL53L0X!
                          Init sensor_vl53l0x_top failed...
Init sensor_vl53l0x_left failed...
Init sensor_vl53l0x_right failed...`

The reported error code is -50. The sensor is available on I2C when I readout registers.

The kit is working correctly using the ST provided GUI-tool and also with own code. I can measure distances and so on. 

Do you have a clue, why it is not working using the Arduino environment with this library?

**Comment by fpistm** [comment]
Hi @stumpf-das 
we have found some regressions on I2C which was fixed on the core master.
It is probably linked to your issue.
Fix will be available thanks the board manager with the next release 1.9.0 of the core

**Comment by cparata** [comment]
Hi @stumpf-das ,
which version of the STM32duino Core are you using? With STM32duino Core v1.8.0 there is an I2C issue. So, I suggest to test the library with STM32duino Core v1.7.0 until the STM32duino Core v1.9.0 will be published.
Best Regards,
Carlo

**Comment by stumpf-das** [comment]
Hi @fpistm , hi @cparata ,
thanks for the hint. I forgot to add the version for STM32duino Core I used. It was actually 1.8.0.

I just installed 1.7.0 and and works right out of the box! There really seems to be an issue with the 1.8.0. What a pitty, I didn't worked that out earlier. It did really eat up some time.

Probably there is a place in the README.md to warn others.

Kind regards,
Wolfram
